version: 2
updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
    groups:
      all:
        patterns:
          - "*"
    commit-message:
      prefix: chore
  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      all:
        patterns:
          - "*"
    commit-message:
      prefix: chore
