repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 1f1e8bf348ff38fc88619a38d3ca4d9c56abea49  # frozen: v0.16.5
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: b60edd5a6e1cdaa6da32da88e01bb83f760e61a8  # frozen: v2.28.2
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/codespell-project/codespell
    rev: 57b21406f092110c18776e39b0bda50d37c945c8  # frozen: v2.4.3
    hooks:
      - id: codespell

  - repo: https://github.com/rstcheck/rstcheck
    rev: 27a8027d6c6df787891a01b76e8298bac493fb58  # frozen: v6.3.0
    hooks:
      - id: rstcheck

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
        args: [ --unsafe ]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: trailing-whitespace
