repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 3b3f7c3f57fe9925356faf5fe6230835138be230  # frozen: v0.15.17
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: ca620e0df5ae9a02b7b81a6e4c954894f043ce42  # frozen: v2.24.1
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/codespell-project/codespell
    rev: 2ccb47ff45ad361a21071a7eedda4c37e6ae8c5a  # frozen: v2.4.2
    hooks:
      - id: codespell

  - repo: https://github.com/rstcheck/rstcheck
    rev: 77490ffa33bfc0928975ae3cf904219903db755d  # frozen: v6.2.5
    hooks:
      - id: rstcheck

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
        args: [ --unsafe ]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: trailing-whitespace
