repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: cb8c523fd4835aba42af70f4cad5568db4df0b6c  # frozen: v0.16.0
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 3632ea90e7641b574983ddf3a11ccedefff3c881  # frozen: v2.25.3
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/codespell-project/codespell
    rev: 57b21406f092110c18776e39b0bda50d37c945c8  # frozen: v2.4.3
    hooks:
      - id: codespell

  - repo: https://github.com/rstcheck/rstcheck
    rev: 77490ffa33bfc0928975ae3cf904219903db755d  # frozen: v6.2.5
    hooks:
      - id: rstcheck

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
        args: [ --unsafe ]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: trailing-whitespace
