requires = [ "tox>=4.6" ]

[env_run_base]
runner = "uv-venv-lock-runner"
package = "wheel"
dependency_groups = [ "tests" ]
commands = [
  [ "uv", "run", "pytest", { replace = "posargs", default = [ "--cov", "query_exporter/" ], extend = true } ]
]

[env.check]
dependency_groups = [ "tests", "types" ]
commands = [
  [
    "uv",
    "run",
    "mypy",
    "integration_tests",
    "query_exporter",
    "tests",
    { replace = "posargs", default = [], extend = true }
  ]
]

[env.format]
package = "skip"
commands = [
  [ "uv", "tool", "run", "ruff", "format", "integration_tests", "query_exporter", "tests" ],
  [ "uv", "tool", "run", "ruff", "check", "--fix", "integration_tests", "query_exporter", "tests" ],
  [ "-", "uv", "tool", "run", "pyproject-fmt", "pyproject.toml" ],
  [ "-", "uv", "tool", "run", "tox-toml-fmt", "tox.toml" ],
]

[env.integration-tests]
dependency_groups = [ "integration-tests" ]
commands = [ [ "pytest", "-o", "testpaths=integration_tests", { replace = "posargs", default = [], extend = true } ] ]

[env.lint]
package = "skip"
commands = [
  [ "uv", "tool", "run", "ruff", "check", "integration_tests", "query_exporter", "tests" ],
  [ "uv", "tool", "run", "pyproject-fmt", "--check", "pyproject.toml" ],
  [ "uv", "tool", "run", "tox-toml-fmt", "--check", "tox.toml" ],
]

[env.run]
package = "editable"
commands = [ [ "uv", "run", "query-exporter", { replace = "posargs", default = [], extend = true } ] ]
