requires = [ "tox>=4.6" ]

[env_run_base]
runner = "uv-venv-lock-runner"
package = "wheel"
dependency_groups = [ "dev", "tests" ]
commands = [ [ "pytest", { replace = "posargs", default = [ "--cov", "query_exporter/" ], extend = true } ] ]

[env.check]
dependency_groups = [ "dev", "tests", "types" ]
commands = [ [ "ty", "check", { replace = "posargs", default = [], extend = true } ] ]

[env.integration-tests]
dependency_groups = [ "integration-tests" ]
commands = [ [ "pytest", "-o", "testpaths=integration_tests", { replace = "posargs", default = [], extend = true } ] ]

[env.lint]
package = "skip"
dependency_groups = [ "dev" ]
commands = [ [ "pre-commit", "run", "--all-files" ] ]

[env.run]
package = "editable"
commands = [ [ "query-exporter", { replace = "posargs", default = [], extend = true } ] ]
