name: query-exporter
version: git
summary: Export Prometheus metrics from SQL queries
description: |
  query-exporter is a Prometheus exporter which allows collecting metrics from
  database queries, at specified time intervals or when a request to the
  metrics endpoint is performed.

  Each query can be run on multiple databases, and update multiple metrics.

  The snap provides both the `query-exporter` command and a deamon instance of
  the command, managed via a Systemd service.
  To run the latter:

    - create `/var/snap/query-exporter/current/config.yaml` with the desired
      configuration
    - optionally, create a `/var/snap/query-exporter/current/.env` file with
      environment variables definitions for additional config options
    - run `sudo snap restart query-exporter`

  Currently supported databases are:

    - PostgreSQL (`postgresql://`)
    - MySQL (`mysql://`)
    - SQLite (`sqlite://`)
    - Microsoft SQL Server (`mssql://`)
    - IBM DB2 (`db2://`) on supported architectures (x86_64, ppc64le and
      s390x)
    - ClickHouse (`clickhouse+native://`)
icon: logo.svg
license: GPL-3.0+
website: https://github.com/albertodonato/query-exporter
source-code: https://github.com/albertodonato/query-exporter
contact: https://github.com/albertodonato/query-expoter/issues
issues: https://github.com/albertodonato/query-exporter/issues

confinement: strict
grade: stable
base: core24
platforms:
  amd64:
  arm64:

apps:
  daemon:
    command: daemon.sh
    daemon: simple
    plugs:
      - network-bind
      - network
  query-exporter:
    command: bin/query-exporter
    plugs:
      - home
      - network-bind
      - network
    completer: query-exporter.completion

parts:
  query-exporter:
    plugin: python
    source: .
    source-type: git
    python-requirements:
      - requirements.txt
    python-packages:
      - .
      - clickhouse-sqlalchemy
      - ibm-db-sa; platform_machine == 'x86_64'
      - ibm-db-sa; platform_machine == 'ppc64le'
      - mysqlclient
      - psycopg2
      - pyodbc
    build-packages:
      - libmysqlclient-dev
      - libpq-dev
      - libssl-dev
      - pkg-config
      - unixodbc-dev
    stage-packages:
      - libmysqlclient21
      - libodbc2
      - libpq5
      - libxml2
    override-build: |
      craftctl default
      _QUERY_EXPORTER_COMPLETE=bash_source query-exporter > "$CRAFT_PART_INSTALL/query-exporter.completion"
    prime:
      - bin/python3
      - bin/query-exporter
      - etc
      - lib
      - pyvenv.cfg
      - query-exporter.completion
      - usr/lib

  wrappers:
    plugin: dump
    source: snap/local
