name: Docker image

on:
  push:
    branches:
      - main
      - next
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build-base:
    name: Build base image
    if: github.actor == github.repository_owner
    uses: albertodonato/github-workflows/.github/workflows/docker-build-publish.yaml@3228e5616e857e12f3c1b6731436ae0a6e2f573c # v0.0.5
    with:
      image-name: ${{ github.repository }}
      dockerhub-image-name: query-exporter
      dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
      platforms: linux/amd64,linux/arm64
    secrets: inherit

  build-full:
    name: Build full image
    if: github.actor == github.repository_owner
    uses: albertodonato/github-workflows/.github/workflows/docker-build-publish.yaml@3228e5616e857e12f3c1b6731436ae0a6e2f573c # v0.0.5
    needs:
      - build-base
    with:
      image-name: ${{ github.repository }}
      suffix: full
      dockerhub-image-name: query-exporter
      dockerhub-username: ${{ vars.DOCKERHUB_USERNAME }}
      platforms: linux/amd64,linux/arm64
    secrets: inherit
